"""add user_id to credentials

Revision ID: 2ebb8a8e53be
Revises: e22bd86eb1f8
Create Date: 2025-10-07 23:51:36.256667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ebb8a8e53be'
down_revision: Union[str, Sequence[str], None] = 'e22bd86eb1f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'credentials', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'credentials', type_='foreignkey')
    op.drop_column('credentials', 'user_id')
    # ### end Alembic commands ###
